### ISSUE TITLE
ratation acc is 25%

### ISSUE THREAD

**Issue by NanAlbert** [cvl-umass/fsl_ssl#1]
Follow your code, the result is as follows:
**100 Test Rotation Acc = 25.00% +- 0.00%**
The accuracy has been maintained at 25%. Do you know the reason? Thank you!

**Comment by jongchyisu** [comment]
Hi, what setting/args did you run?

**Comment by jongchyisu** [comment]
Hi, could you provide more details about your arguments for the experiment?

**Comment by NanAlbert** [comment]
I feel so sorry for not replying to you in time. I have already solved the problem, and thank you for your reply!

**Comment by onlyyao** [comment]
> Follow your code, the result is as follows: **100 Test Rotation Acc = 25.00% +- 0.00%** The accuracy has been maintained at 25%. Do you know the reason? Thank you!
Hi~, I've met the same question. How did you solve it? Thank you!

**Comment by How-Wang** [comment]
I meet the same problem. Can someone give me the solution?
