### ISSUE TITLE
The rotation acc is  always 25% in the test stage

### ISSUE THREAD

**Issue by LuletterSoul** [cvl-umass/fsl_ssl#5]
Hi, thanks for your great job! I found that the rotation accuracy is always 25%. I used the miniImageNet dataset. The  `base.json`, `novel.json`, and `val.json` are generated by `write_miniImagenet_filelist.py` as you provided. And the other settings remained the same as the default parameters. The training command is as below: 

```
 python train.py --dataset miniImagenet --train_aug --rotation
```

<img width="564" alt="image" src="https://user-images.githubusercontent.com/21377419/167596276-e837a674-ab2e-44ac-8025-651a44fcb6e4.png">

The rotation loss seems to decrease a little. Do you know what causes this problem? Hope for your early response!

**Comment by How-Wang** [comment]
I have same problem.

**Comment by How-Wang** [comment]
@LuletterSoul Can you provide your answer?
